// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpkiufcsrckoexmswzwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpwa2l1ZmNzcmNrb2V4bXN3endrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4OTUyNjAsImV4cCI6MjA2MzQ3MTI2MH0.7oZTfI-O4GG8-UCR9gjzAUKLIwHpuTHyU7ptWXID-Yo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);